<a href="https://colab.research.google.com/github/tensorpig/learning_tensorflow/blob/master/Lists_Arrays_Tensors_Dataframes_and_Datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Let's pretend we have a simple regression like problem. We start out with 3 features describing a robotic spider we're building. For example: number of legs (feature 1), weight (feature 2), and version number (feature 3). Say that we so far built three prototype robots, so have 3 values for each feature. 

In [1]:
feature1 = [1,2,3]
feature2 = [4.0,5.0,6.0]
feature3 = ['100','101','102']
print(type(feature1))

<class 'list'>


We'll look at the various different data structures you will probably run into when doing ML/AI in pyhton and tensorflow. Combining the features into matrices etc. Starting from basic python lists and progressing up to keras Datasets which you will typically feed into your neural network.

First up: the basic python LIST

In [58]:
list2d = [feature1, feature2, feature3] 
print(type(list2d))
print(list2d)
print('({},{})'.format(len(list2d),len(list2d[0]))) #nr of rows and cols
print(list2d[0]) #first row
print([row[0] for row in list2d]) #first col
print(list2d[0][0]) # value at 0,0
print([[row[i] for row in list2d] for i in range(len(list2d[0]))]) # transpose to make more like excel sheet

<class 'list'>
[[1, 2, 3], [4.0, 5.0, 6.0], ['100', '101', '102']]
(3,3)
[1, 2, 3]
[1, 4.0, '100']
1
[[1, 4.0, '100'], [2, 5.0, '101'], [3, 6.0, '102']]
<class 'tuple'>
([1, 2, 3], [4.0, 5.0, 6.0], ['100', '101', '102'])


A python list is a collection of any data types. The items in a list can be lists again, and there are no requirements for the items in a list to be of the same type, or of the same length.

There is also the Tuple, which has () around the feautes instead of []. A Tuple works hte same, but once creatd, cannot be changed.

Next up the Numpy ARRAY

In [3]:
import numpy as np
array2d = np.array([feature1, feature2, feature3], dtype=object)
print(type(array2d))
print(array2d)
print(array2d.shape) #nr of rows and cols
print(array2d[0,:]) #first element/row = array, could also be just array2d[0]
print(array2d[:,0]) #first column, or actually first element from each 1d array in the 2d array
print(array2d[0,0]) # value at 0,0
print(array2d.transpose()) #more like excel sheet

<class 'numpy.ndarray'>
[[1 2 3]
 [4.0 5.0 6.0]
 ['100' '101' '102']]
(3, 3)
[1 2 3]
[1 4.0 '100']
1
[[1 4.0 '100']
 [2 5.0 '101']
 [3 6.0 '102']]


A numpy array expects all items to be of the same type. If the dtype=object is not used above, all of the values will be converted to strings as this is the minimum type that can hold all values. A numpy array can handle features of different length, but then each element in the array will be of type 'list', so no direct indexing like you would expect from a matrix.

Next up the Pandas DATAFRAME

In [4]:
import pandas as pd
dataframe = pd.DataFrame()
dataframe['feature1'] = feature1
dataframe['feature2'] = feature2
dataframe['feature3'] = feature3
print(type(dataframe))
print(dataframe)
print(dataframe.shape)
print(dataframe.iloc[0].tolist()) # first row, without .tolist() it also shows the column headers as row headers. You can also use loc[0], where 0 is now value in the index column (same as row number here)
print(dataframe['feature1'].tolist()) #first column, without .tolist() it also shows the index. You can also use .iloc[:,0]
print(dataframe.iloc[0,0]) #value at 0,0

<class 'pandas.core.frame.DataFrame'>
   feature1  feature2 feature3
0         1       4.0      100
1         2       5.0      101
2         3       6.0      102
(3, 3)
[1, 4.0, '100']
[1, 2, 3]
1


A Pandas dataframe is basically an excel sheet. It can handle features with different datatypes, but not different lengths of feature arrays.

Next up TENSORs

In [5]:
import tensorflow as tf
feature3int = [int(x) for x in feature3 ] # map string values to numerical representation (in this case the string is a number so easy)
tensorRank2 = tf.constant([feature1, feature2, feature3int], dtype=float)
print(type(tensorRank2))
print(tensorRank2)
print(tensorRank2.shape)
print(tensorRank2[0,:].numpy()) #first row, without .numpy() a tensor object is returned. Could also use just [0]
print(tensorRank2[:,0].numpy()) #first col
print(tensorRank2[0,0].numpy()) # value at 0,0
print(tf.transpose(tensorRank2)) # more like excel sheet

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[  1.   2.   3.]
 [  4.   5.   6.]
 [100. 101. 102.]], shape=(3, 3), dtype=float32)
(3, 3)
[1. 2. 3.]
[  1.   4. 100.]
1.0
tf.Tensor(
[[  1.   4. 100.]
 [  2.   5. 101.]
 [  3.   6. 102.]], shape=(3, 3), dtype=float32)


Tensors are n-dimensional generalizations of matrices. Vectors are tensors, and can be seen as 1-dimensional matrices. All are represented using n-dimensional arrays with a uniform type, and features with uniform length. I had to convert feature3 list to int, although I could also have converted feature1 and fature2 lists to strings.

Next up DATASETs

In [57]:
feature1f = [float(x) for x in feature1 ] # map string values to numerical representation
feature3f = [float(x) for x in feature3 ] # map string values to numerical representation
dataset = tf.data.Dataset.from_tensor_slices([feature1f, feature2, feature3f])
print(type(dataset))
print(dataset.element_spec)
print(dataset)
print(list(dataset.as_numpy_iterator()))
print(list(dataset.take(1).as_numpy_iterator())[0]) #first "row"
print(list(dataset.take(1).as_numpy_iterator())[0][0]) # value at 0,0


<class 'tensorflow.python.data.ops.dataset_ops.TensorSliceDataset'>
TensorSpec(shape=(3,), dtype=tf.float32, name=None)
<TensorSliceDataset shapes: (3,), types: tf.float32>
[array([1., 2., 3.], dtype=float32), array([4., 5., 6.], dtype=float32), array([100., 101., 102.], dtype=float32)]
[1. 2. 3.]
1.0


A Dataset is a sequence of elements, each element consisting of one or more components. In this case, each element of the Dataset is a TensorSliceDataset of shape (3,) which, when converted to a list, is shown to wrap around an array of 3 floats as expected.

A Dataset is aimed at creating data pipelines, which get data from somewhere, process and transform it (typically in smaller batches), and then output it to a neural network (or somewhere else). A main goal of such a piepline is to avoid getting (all) the data in memory and enable large data sets to be handled in smaller peices. As such, getting values for specific elements in the dataset is not what Dataset are built for (and it shows).  

In [61]:
datasett = tf.data.Dataset.from_tensor_slices((feature1, feature2, feature3))
print(type(datasett))
print(datasett.element_spec)
print(datasett)
print(list(datasett.as_numpy_iterator()))

<class 'tensorflow.python.data.ops.dataset_ops.TensorSliceDataset'>
(TensorSpec(shape=(), dtype=tf.int32, name=None), TensorSpec(shape=(), dtype=tf.float32, name=None), TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None))
<TensorSliceDataset shapes: ((), (), (), ()), types: (tf.int32, tf.float32, tf.string, tf.int32)>
[(1, 4.0, b'100', -1), (2, 5.0, b'101', -2), (3, 6.0, b'102', -3)]


If you create a Dataset from a tuple of arrays, instead of an array of arrays, you can see each element is now a tuple of 3 TensorSpec of different type and shape () which can be seen wrap around a tuple for transposed feature values. 

This shows that from_tensor_slices() "slices" the tensors along the first dimension